export const LocalStorageVars = {
  lastUpdate: 'lastUpdate',
  mexicoCarPlatesInventory: 'mexicoCarPlatesInventory',
  defaultAccessTokenID: 'defaultAccessTokenID',
};

export const MEX_CODES = new Map([
  ['AGS', 'Aguascalientes'],
  ['BC', 'Baja California'],
  ['BCS', 'Baja California Sur'],
  ['CAMP', 'Campeche'],
  ['CHIS', 'Chiapas'],
  ['CHIH', 'Chihuahua'],
  ['COAH', 'Coahuila'],
  ['COL', 'Colima'],
  ['DF', 'Distrito Federal'],
  ['DGO', 'Durango'],
  ['GTO', 'Guanajuato'],
  ['GRO', 'Guerrero'],
  ['HGO', 'Hidalgo'],
  ['JAL', 'Jalisco'],
  ['MEX', 'México'],
  ['MICH', 'Michoacán'],
  ['MOR', 'Morelos'],
  ['NAY', 'Nayarit'],
  ['NL', 'Nuevo León'],
  ['OAX', 'Oaxaca'],
  ['PUE', 'Puebla'],
  ['QRO', 'Querétaro'],
  ['QR', 'Quintana Roo'],
  ['SLP', 'San Luis Potosí'],
  ['SIN', 'Sinaloa'],
  ['SON', 'Sonora'],
  ['TAB', 'Tabasco'],
  ['TAMPS', 'Tamaulipas'],
  ['TLAX', 'Tlaxcala'],
  ['VER', 'Veracruz'],
  ['YUC', 'Yucatán'],
  ['ZAC', 'Zacatecas'],
]);
